CREATE DATABASE Exercicios;

USE Exercicios

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(50) NOT NULL,
)

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
	Nome VARCHAR(50) NOT NULL,
	CRMV CHAR(11) NOT NULL,
)

CREATE TABLE DONO 
(
	IdDono INT PRIMARY KEY IDENTITY,
	NomeDono VARCHAR(50) NOT NULL,
)

CREATE TABLE Raca
(
	IdRaca INT PRIMARY KEY IDENTITY,
	DescricaoRaca VARCHAR(50) NOT NULL
)

CREATE TABLE Tipo
(
	IdTipo INT PRIMARY KEY IDENTITY,
	DescricaoTipo VARCHAR(50) NOT NULL
)

CREATE TABLE Pet
(
	IdPet INT PRIMARY KEY IDENTITY,
	IdTipo INT FOREIGN KEY REFERENCES Tipo(IdTipo),
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
	IdDono INT FOREIGN KEY REFERENCES DONO(IdDono),
	NomePet VARCHAR(50) NOT NULL,
	DataNascimento VARCHAR(12) NOT NULL,
)

CREATE TABLE Atendimento
(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),
	Descricao VARCHAR(50),
	DataAtendimento CHAR(12)
)