CREATE DATABASE Exercicios;

USE Exercicios;

CREATE TABLE Pessoa
(
  IdPessoa INT PRIMARY KEY IDENTITY,
  Nome VARCHAR(50) NOT NULL,
  CNH CHAR(11) NOT NULL,
)

CREATE TABLE Email
(
	IdEmail INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa),
	Endereco VARCHAR(50) NOT NULL
)

CREATE TABLE Telefone
(
	IdTelefone INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa),
	Telefone VARCHAR(30) NOT NULL
)